image: eroslab.cr.usgs.gov:4567/lsrd/espa-api:espa-api-ci_latest

variables:
  GIT_STRATEGY: clone
  COMMIT: ${CI_COMMIT_SHORT_SHA}
  ESPA_ENV: dev
  ESPA_CONFIG_PATH: ${CI_PROJECT_DIR}/run/config.ini
  ESPA_API_EMAIL_RECEIVE: someone@nowhere.com
  PYTHONPATH: ${PYTHONPATH}:${CI_PROJECT_DIR}
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

services:
  - docker:19.03.1-dind

before_script:
  - export ESPA_MEMCACHE_HOST=${DOCKER_PORT_2375_TCP_ADDR}:30070
  - export ESPA_PG_TEST_HOST=${DOCKER_PORT_2375_TCP_ADDR}
  - export ESPA_PG_TEST_PORT=30080
  - make docker-deps-up
  - pip install -r setup/requirements.txt

test:
  script:
    - ${CI_PROJECT_DIR}/run/runtests
  tags:
    - docker
    - eros
    - lsrd

after_script:
  - make docker-deps-down
