#!/bin/sh

if [[ ! -e "$ESPA_CONFIG_PATH" ]]; then
	echo "Missing Database configuration $ESPA_CONFIG_PATH"
	exit 1
fi

#python -m unittest discover test
nose2 -v --log-level ERROR --fail-fast --with-coverage

# flake8 api
# pylint api

