products:
  source_metadata:
    category: source
    title: "Input Product Metadata"
    display_rank: 1
  l1:
    category: source
    title: "Input Products"
    display_rank: 0
  pixel_qa:
    category: l2p
    title: "Pixel QA"
    display_rank: 4
  toa:
    category: l2p
    title: "Top of Atmosphere Reflectance"
    display_rank: 2
  bt:
    category: l2p
    title: "Brightness Temperature"
    display_rank: 3
  sr:
    category: l2p
    title: "Surface Reflectance"
    display_rank: 0
  orca:
    category: l2p
    title: "Surface Water Reflectance"
    display_rank: 1
  st:
    category: l2p
    title: "Surface Temperature"
    display_rank: 1
  stalg_split_window:
    category: l2p
    title: "Split Window ST"
    display_rank: 1
  stalg_single_channel:
    category: l2p
    title: "Single Channel ST"
    display_rank: 2
  reanalsrc_narr:
    category: l2p
    title: "Reanalysis Source NARR"
    display_rank: 1
  reanalsrc_merra2:
    category: l2p
    title: "Reanalysis Source MERRA2"
    display_rank: 2
  reanalsrc_fp:
    category: l2p
    title: "Reanalysis Source FP"
    display_rank: 3
  reanalsrc_fpit:
    category: l2p
    title: "Reanalysis Source FPIT"
    display_rank: 4
  swe:
    category: l3p
    title: "Dynamic Surface Water Extent"
    display_rank: 0
  sr_ndvi:
    category: indices
    title: "NDVI"
    display_rank: 0
  sr_evi:
    category: indices
    title: "EVI"
    display_rank: 1
  sr_savi:
    category: indices
    title: "SAVI"
    display_rank: 2
  sr_msavi:
    category: indices
    title: "MSAVI"
    display_rank: 3
  sr_ndmi:
    category: indices
    title: "NDMI"
    display_rank: 4
  sr_nbr:
    category: indices
    title: "NBR"
    display_rank: 5
  sr_nbr2:
    category: indices
    title: "NBR2"
    display_rank: 6
  s2_sr:
    category: l2p
    title: "SENTINEL-2 SR"
    display_rank: 0
  s2_ndvi:
    category: indices
    title: "SENTINEL-2 NDVI"
    display_rank: 7
  s2_evi:
    category: indices
    title: "SENTINEL-2 EVI"
    display_rank: 8
  s2_savi:
    category: indices
    title: "SENTINEL-2 SAVI"
    display_rank: 9
  s2_msavi:
    category: indices
    title: "SENTINEL-2 MSAVI"
    display_rank: 10
  s2_ndmi:
    category: indices
    title: "SENTINEL-2 NDMI"
    display_rank: 11
  s2_nbr:
    category: indices
    title: "SENTINEL-2 NBR"
    display_rank: 12
  s2_nbr2:
    category: indices
    title: "SENTINEL-2 NBR2"
    display_rank: 13
  modis_ndvi:
    category: indices
    title: "MODIS Daily NDVI"
    display_rank: 14
  viirs_ndvi:
    category: indices
    title: "VIIRS Daily NDVI"
    display_rank: 15
  stats:
    category: stats
    title: "Summary Statistics"
    display_rank: 0

categories:
  source:
    title: "Source Products"
    display_rank: 0
  l2p:
    title: "Level-2 Products"
    display_rank: 1
  l3p:
    title: "Level-3 Products"
    display_rank: 2
  indices:
    title: "Spectral Indices"
    display_rank: 3
  stats:
    title: "Plotting & Statistics"
    display_rank: 4
